#在application.properties/或者application.yml文件中添加数据库配置信息.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo_inseparable?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
  resources:
    static-locations: file:/path/to/custom/static/imgs/